DATASET:
    batch_size: 1
    num_workers: 0
    quant:
        format: "VideoDataset"
        data_prefix: "../../data/k400/videos"
        file_path: "../../data/k400/val_small_videos.list"

PIPELINE:
    quant:
        decode:
            name: "VideoDecoder"
            backend: "decord"
        sample:
            name: "Sampler"
            num_seg: 25
            seg_len: 1
            valid_mode: True
            linspace_sample: True
        transform:
            - Scale:
                short_size: 256
                fixed_ratio: False
                backend: 'cv2'
            - TenCrop:
                target_size: 224
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

inference_model_dir: "../../inference/ppTSN"
quant_output_dir: "../../inference/ppTSN/quant_model"

model_name: "ppTSN"
log_level: "INFO" #Optional, the logger level. default: "INFO"
