MODEL: #MODEL field
    framework: "Resolver2D" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
    backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
        name: 'WAFPNet'
        num_residual_layer: 9
        num_refine_layer: 9
    head:
        name: 'WAFPHead' # only compute loss and metrics.
    runtime_cfg:
        val:
            mode: patch  # must be patch in validate
            scale: 4  # must be 4
            patch_size: 61  # must be 61
        test:
            mode: patch
            scale: 4
            patch_size: 61
        infer:
            mode: patch
            scale: 4
            patch_size: 61


DATASET: #DATASET field
    batch_size: 64 #Mandatory, bacth size
    valid_batch_size: 1
    test_batch_size: 1
    num_workers: 1 #Mandatory, XXX the number of subprocess on each GPU.
    train:
        format: "HDF5Dataset"
        file_path: "data/depthSR/train_depth_x4_noise.h5"
    valid:
        format: "MatDataset"
        data_prefix: "data/depthSR/val"
        file_path: "data/depthSR/val.list"
    test:
        format: "MatDataset"
        data_prefix: "data/depthSR/val"
        file_path: "data/depthSR/val.list"

PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
    valid:
        decode:
            name: 'MatDecoder'
    test:
        decode:
            name: 'MatDecoder'

OPTIMIZER: #OPTIMIZER field
    name: 'Momentum' #Mandatory, the type of optimizer, associate to the 'paddlevideo/solver/'
    momentum: 0.9
    learning_rate:
        name : 'StepDecay'
        learning_rate: 0.1
        step_size: 20
        gamma: 0.1
    weight_decay:
        name: 'L2'
        value: 0.0001
    grad_clip:
        name: 'ClipGradByGlobalNorm'
        value: 0.4

METRIC:
    name: 'RMSEMetric'
    scale: 4

INFERENCE:
    name: 'WAFP_Inference_helper'
    height: 368
    width: 440

model_name: "WAFP"
log_interval: 100 #Optional, the interal of logger, default:10
save_interval: 10
epochs: 80 #Mandatory, total epoch
log_level: "INFO" #Optional, the logger level. default: "INFO"
